//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Databases
{
    using System.Collections;
    using System.Collections.Generic;
    using UnityEngine;
    using Nawlian.Lib.Utils.Database;
    using Nawlian.Lib.Utils;
    using System.Linq;
    
    
    public class Database : Singleton<Database>
    {
        
        private Nawlian.Lib.Utils.Database.DatabaseData _databaseAsset;
        
        public virtual Nawlian.Lib.Utils.Database.DatabaseData DatabaseAsset
        {
            get
            {
                return _databaseAsset ??= Resources.Load<DatabaseData>("Data/Database");
            }
        }
        
        public class Templates
        {
            
            public class Editor
            {
                
                public static UnityEngine.GameObject Player = (UnityEngine.GameObject)Instance.DatabaseAsset.Sections[0].Sections[0].Assets[0].Prefab;
                
                public static IEnumerable<T> All<T>()
                    where T : UnityEngine.Object
                {
                    UnityEngine.Object[] all = new UnityEngine.Object[1] {Player};
                    return all.Where(x => x is T).Select(x => (T)x);
                }
            }
        }
    }
}
